events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream backend {
        server backend:8000 max_fails=3 fail_timeout=30s;
    }

    upstream frontend_app {
        # PRODUCCIÓN: Ya no apunta a 3000 (node de desarrollo), ahora apunta a 80 (nginx de react)
        server frontend:80;
    }

    server {
        listen 80;
        server_name localhost;
        client_max_body_size 100M;

        location /fast-food/admin {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # MEDIA FILES - Imágenes de productos
        location /media/ {
            alias /usr/share/nginx/html/media/;
            expires 30d;
            add_header Cache-Control "public, immutable";
            add_header Access-Control-Allow-Origin *;
        }

        location /api/authentication/ {
            rewrite ^/api/authentication/(.*) /auth/api/authentication/$1 break;
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/users/ {
            rewrite ^/api/users/(.*) /auth/api/users/$1 break;
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/roles/ {
            rewrite ^/api/roles/(.*) /auth/api/roles/$1 break;
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/fast-food/ {
            rewrite ^/api/fast-food/(.*) /fast-food/$1 break;
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # STATIC FILES - REACT FRONTEND
        location /static/js/ {
            proxy_pass http://frontend_app;
            proxy_set_header Host $host;
        }
        location /static/css/ {
            proxy_pass http://frontend_app;
            proxy_set_header Host $host;
        }
        location /static/media/ {
            proxy_pass http://frontend_app;
            proxy_set_header Host $host;
        }

        # STATIC FILES - DJANGO BACKEND
        location /static/ {
            alias /usr/share/nginx/html/static/backend/;
            expires 30d;
            add_header Cache-Control "public, immutable";
            access_log off;
        }

        location / {
            proxy_pass http://frontend_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
}
