# Generated by Django 5.0.1 on 2025-12-04 09:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Orden')),
                ('order_type', models.CharField(choices=[('dine_in', 'Comer Aquí'), ('takeout', 'Para Llevar'), ('delivery', 'Delivery'), ('drive_thru', 'Drive-Thru')], default='dine_in', max_length=20, verbose_name='Tipo de Orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En Preparación'), ('ready', 'Listo'), ('delivering', 'En Camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado de Pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Impuestos')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de Envío')),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Propina')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instrucciones Especiales')),
                ('table_number', models.CharField(blank=True, max_length=10, verbose_name='Número de Mesa')),
                ('estimated_prep_time', models.PositiveIntegerField(default=15, verbose_name='Tiempo estimado de preparación (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Listo')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('reference', models.TextField(blank=True, help_text='Casa blanca, portón verde, etc.', verbose_name='Referencia')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nombre de Contacto')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('driver_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Repartidor')),
                ('driver_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Repartidor')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora estimada de entrega')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Recogido a las')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado a las')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Información de Delivery',
                'verbose_name_plural': 'Información de Deliveries',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Línea')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.product', verbose_name='Producto')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.size', verbose_name='Tamaño')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.extra', verbose_name='Extra')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='orders.orderitem', verbose_name='Item de Orden')),
            ],
            options={
                'verbose_name': 'Extra de Item',
                'verbose_name_plural': 'Extras de Items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En Preparación'), ('ready', 'Listo'), ('delivering', 'En Camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('rejected', 'Rechazado')], max_length=20, verbose_name='Estado Anterior')),
                ('to_status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En Preparación'), ('ready', 'Listo'), ('delivering', 'En Camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('rejected', 'Rechazado')], max_length=20, verbose_name='Nuevo Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('changed_by', models.CharField(blank=True, max_length=100, verbose_name='Cambiado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'created_at'], name='orders_orde_custome_242823_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='orders_orde_order_t_d697ad_idx'),
        ),
    ]
