# Generated by Django 5.0.1 on 2025-12-04 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decirlo')], max_length=1, null=True)),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado/Provincia')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('country', models.CharField(blank=True, default='Ecuador', max_length=100, verbose_name='País')),
                ('customer_type', models.CharField(choices=[('regular', 'Cliente Regular'), ('vip', 'Cliente VIP'), ('corporate', 'Cliente Corporativo'), ('student', 'Estudiante'), ('first_time', 'Primera Vez')], default='regular', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Cliente VIP')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Preferencias')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total de pedidos')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total gastado')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Último pedido')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor promedio de pedido')),
                ('newsletter_subscribed', models.BooleanField(default=True, verbose_name='Suscrito al newsletter')),
                ('marketing_emails', models.BooleanField(default=True, verbose_name='Acepta emails de marketing')),
                ('marketing_sms', models.BooleanField(default=True, verbose_name='Acepta SMS de marketing')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('registered_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['customer_type'], name='customers_c_custome_47da94_idx'), models.Index(fields=['is_vip'], name='customers_c_is_vip_72cf8e_idx'), models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('home', 'Casa'), ('work', 'Trabajo'), ('billing', 'Facturación'), ('shipping', 'Envío'), ('other', 'Otro')], default='home', max_length=20)),
                ('is_default', models.BooleanField(default=False, verbose_name='Dirección principal')),
                ('street', models.CharField(max_length=255, verbose_name='Calle y número')),
                ('apartment', models.CharField(blank=True, max_length=100, verbose_name='Departamento/Oficina')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado/Provincia')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('country', models.CharField(default='Ecuador', max_length=100, verbose_name='País')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instrucciones especiales')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Dirección del cliente',
                'verbose_name_plural': 'Direcciones de clientes',
                'ordering': ['-is_default', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_tier', models.CharField(choices=[('bronze', 'Bronce (0-999 puntos)'), ('silver', 'Plata (1000-4999 puntos)'), ('gold', 'Oro (5000-14999 puntos)'), ('platinum', 'Platino (15000+ puntos)')], default='bronze', max_length=20)),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='Puntos actuales')),
                ('total_points_earned', models.PositiveIntegerField(default=0, verbose_name='Puntos totales ganados')),
                ('total_points_redeemed', models.PositiveIntegerField(default=0, verbose_name='Puntos totales canjeados')),
                ('tier_achieved_date', models.DateTimeField(blank=True, null=True)),
                ('next_tier_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progreso al siguiente nivel (%)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='Envío gratis')),
                ('priority_service', models.BooleanField(default=False, verbose_name='Servicio prioritario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Programa de lealtad',
                'verbose_name_plural': 'Programas de lealtad',
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyaltyHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Ganancia'), ('redeem', 'Canje'), ('adjustment', 'Ajuste'), ('expiration', 'Expiración')], max_length=20)),
                ('points_change', models.IntegerField(verbose_name='Cambio de puntos')),
                ('balance_after', models.PositiveIntegerField(verbose_name='Saldo después')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Razón')),
                ('order_reference', models.CharField(blank=True, max_length=50, verbose_name='Referencia de pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customers.customerloyalty')),
            ],
            options={
                'verbose_name': 'Historial de lealtad',
                'verbose_name_plural': 'Historiales de lealtad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('general', 'General'), ('preference', 'Preferencia'), ('issue', 'Problema'), ('complaint', 'Queja'), ('praise', 'Elogio'), ('allergy', 'Alergia'), ('reminder', 'Recordatorio')], default='general', max_length=20)),
                ('content', models.TextField(verbose_name='Contenido de la nota')),
                ('created_by_name', models.CharField(blank=True, max_length=100, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivada')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Nota del cliente',
                'verbose_name_plural': 'Notas de clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                ('device_token', models.CharField(max_length=255, unique=True, verbose_name='Token del dispositivo')),
                ('device_id', models.CharField(blank=True, max_length=255, verbose_name='ID del dispositivo')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='Versión de la app')),
                ('os_version', models.CharField(blank=True, max_length=20, verbose_name='Versión del SO')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo del dispositivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Último uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Dispositivo del cliente',
                'verbose_name_plural': 'Dispositivos de clientes',
                'unique_together': {('customer', 'device_token')},
            },
        ),
    ]
