# Generated by Django 5.0.1 on 2025-12-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_last_login_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cedula',
            field=models.CharField(blank=True, help_text='Documento de identificación único', max_length=20, null=True, unique=True, verbose_name='Cédula / RUC'),
        ),
    ]
