# Generated by Django 5.0.1 on 2025-12-05 21:18

import apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menu_item_image_path, verbose_name='Imagen'),
        ),
    ]
