# Generated by Django 5.0.1 on 2025-12-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En Preparación'), ('ready', 'Listo'), ('delivering', 'En Camino'), ('delivered', 'Entregado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En Preparación'), ('ready', 'Listo'), ('delivering', 'En Camino'), ('delivered', 'Entregado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('rejected', 'Rechazado')], max_length=20, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En Preparación'), ('ready', 'Listo'), ('delivering', 'En Camino'), ('delivered', 'Entregado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('rejected', 'Rechazado')], max_length=20, verbose_name='Nuevo Estado'),
        ),
    ]
