# Generated by Django 5.0.1 on 2026-05-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_discount_percentage_orderitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='efectivo', max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago'),
        ),
    ]
