# Generated by Django 5.0.1 on 2025-12-04 08:57

import apps.menu.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='menu/combos/', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.menu.models.category_image_path, verbose_name='Imagen')),
                ('color', models.CharField(blank=True, help_text='Código hexadecimal, ej: #FF5733', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono para usar en frontend', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='menu_catego_is_acti_afc8ab_idx'), models.Index(fields=['slug'], name='menu_catego_slug_6d0e16_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to=apps.menu.models.menu_item_image_path, verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías')),
                ('ingredients', models.TextField(blank=True, verbose_name='Ingredientes')),
                ('allergens', models.CharField(blank=True, help_text='Ej: Gluten, Lácteos, Huevo', max_length=255, verbose_name='Alergenos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_new', models.BooleanField(default=False, verbose_name='Nuevo')),
                ('prep_time', models.PositiveIntegerField(default=10, verbose_name='Tiempo de preparación (min)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/extras/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='extras', to='menu.product', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Extra/Adicional',
                'verbose_name_plural': 'Extras/Adicionales',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComboProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('is_selectable', models.BooleanField(default=False, help_text='El cliente puede elegir de varias opciones', verbose_name='Seleccionable')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_products', to='menu.combo', verbose_name='Combo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto del Combo',
                'verbose_name_plural': 'Productos del Combo',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: Pequeño, Mediano, Grande', max_length=50, verbose_name='Nombre')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Adicional al precio base. Puede ser negativo para descuento', max_digits=10, verbose_name='Ajuste de precio')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='menu.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Tamaño',
                'verbose_name_plural': 'Tamaños',
                'ordering': ['product', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'is_available'], name='menu_produc_categor_5ce543_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='menu_produc_is_feat_beb8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='menu_produc_slug_67bd16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('product', 'name')},
        ),
    ]
