# Generated by Django 5.0.1 on 2026-06-04 23:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('unit', models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo (kg)'), ('g', 'Gramo (g)'), ('l', 'Litro (L)'), ('ml', 'Mililitro (ml)'), ('oz', 'Onza (oz)'), ('lb', 'Libra (lb)')], default='unit', max_length=20, verbose_name='Unidad de medida')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock Actual')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock Mínimo')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo por unidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insumo / Materia Prima',
                'verbose_name_plural': 'Insumos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Ingreso (Compra/Reabastecimiento)'), ('out', 'Egreso (Desecho/Pérdida)'), ('sale', 'Egreso por Venta'), ('adjustment', 'Ajuste de Inventario')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo / Razón')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='ID Referencia (Venta/Factura)')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Registrado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='menu.supply', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Movimiento de Bodega',
                'verbose_name_plural': 'Movimientos de Bodega',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad requerida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='menu.product', verbose_name='Producto')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='menu.size', verbose_name='Tamaño (Opcional)')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='menu.supply', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Receta',
                'unique_together': {('product', 'size', 'supply')},
            },
        ),
    ]
