# Generated by Django 5.0.1 on 2026-06-10 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_supply_supplymovement_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplymovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Ingreso (Compra/Reabastecimiento)'), ('out', 'Egreso (Desecho/Pérdida)'), ('sale', 'Egreso por Venta'), ('adjustment', 'Ajuste de Inventario'), ('production_out', 'Egreso por Producción'), ('production_in', 'Ingreso por Producción')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('output_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Cantidad generada por batch')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by_recipes', to='menu.supply', verbose_name='Insumo de salida')),
            ],
            options={
                'verbose_name': 'Receta de Producción',
                'verbose_name_plural': 'Recetas de Producción',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_multiplier', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Multiplicador (cantidad de batches)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Realizado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de producción')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='menu.recipe', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeSupply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad requerida por batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.recipe', verbose_name='Receta')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_supplies', to='menu.supply', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta de Producción',
                'verbose_name_plural': 'Ingredientes de Recetas de Producción',
                'unique_together': {('recipe', 'supply')},
            },
        ),
    ]
