# Generated by Django 5.0.1 on 2026-06-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_recipe_production_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='is_production_item',
            field=models.BooleanField(default=False, help_text='Si está marcado, este insumo solo se gestiona desde Mezclas/Producción y no aparece en el POS', verbose_name='Producto de mezcla'),
        ),
    ]
