# Generated by Django 5.0.1 on 2026-06-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_add_is_production_item_to_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='Es Promoción'),
        ),
    ]
