# Generated by Django 5.0.1 on 2025-12-04 09:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register_number', models.CharField(max_length=20, verbose_name='Número de Caja')),
                ('cashier_name', models.CharField(max_length=100, verbose_name='Nombre del Cajero')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=20, verbose_name='Estado')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Efectivo Inicial')),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Efectivo Final')),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Efectivo Esperado')),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diferencia')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Ventas')),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total en Efectivo')),
                ('total_card', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total en Tarjeta')),
                ('total_other', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Otros Métodos')),
                ('transaction_count', models.PositiveIntegerField(default=0, verbose_name='Número de Transacciones')),
                ('opening_notes', models.TextField(blank=True, verbose_name='Notas de Apertura')),
                ('closing_notes', models.TextField(blank=True, verbose_name='Notas de Cierre')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Abierta')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada')),
            ],
            options={
                'verbose_name': 'Caja Registradora',
                'verbose_name_plural': 'Cajas Registradoras',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='USD, COP, EUR, etc.', max_length=3, unique=True, verbose_name='Código ISO')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('symbol', models.CharField(help_text='$, COP$, €, etc.', max_length=10, verbose_name='Símbolo')),
                ('is_default', models.BooleanField(default=False, help_text='La moneda base del sistema (generalmente USD)', verbose_name='Moneda por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('decimal_places', models.PositiveIntegerField(default=2, help_text='Cantidad de decimales (USD=2, JPY=0, etc.)', verbose_name='Decimales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('method_type', models.CharField(choices=[('cash', 'Efectivo'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('bank_transfer', 'Transferencia Bancaria'), ('mobile_payment', 'Pago Móvil'), ('gift_card', 'Tarjeta de Regalo'), ('voucher', 'Vale'), ('online', 'Pago en Línea')], max_length=20, verbose_name='Tipo de Método')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_authorization', models.BooleanField(default=False, help_text='Si requiere aprobación bancaria/procesador', verbose_name='Requiere Autorización')),
                ('gateway_name', models.CharField(blank=True, help_text='Ej: stripe, paypal, payphone', max_length=50, verbose_name='Nombre del Gateway')),
                ('gateway_config', models.JSONField(blank=True, default=dict, help_text='API keys, webhooks, etc.', verbose_name='Configuración del Gateway')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Mínimo')),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Máximo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('reason', models.CharField(choices=[('change_fund', 'Fondo de Cambio'), ('bank_deposit', 'Depósito Bancario'), ('withdrawal', 'Retiro'), ('expense', 'Gasto'), ('adjustment', 'Ajuste'), ('tip', 'Propina'), ('other', 'Otro')], max_length=20, verbose_name='Razón')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('performed_by', models.CharField(max_length=100, verbose_name='Realizado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='payments.cashregister', verbose_name='Caja Registradora')),
            ],
            options={
                'verbose_name': 'Movimiento de Efectivo',
                'verbose_name_plural': 'Movimientos de Efectivo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cashregister',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.currency', verbose_name='Moneda'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=4, help_text='1 unidad de "Desde" = X unidades de "Hacia". Ej: 1 USD = 4200 COP', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Tasa de Cambio')),
                ('source', models.CharField(blank=True, help_text='Manual, API, Banco, etc.', max_length=50, verbose_name='Fuente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, verbose_name='Actualizado por')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='payments.currency', verbose_name='Desde')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='payments.currency', verbose_name='Hacia')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, help_text='Para efectivo, el monto que entregó el cliente', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Recibido')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cambio')),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Monto en la moneda base de la orden', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Original')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa usada en el momento del pago', max_digits=12, null=True, verbose_name='Tasa de Cambio Aplicada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('partially_refunded', 'Parcialmente Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('transaction_id', models.CharField(blank=True, help_text='ID del procesador de pagos', max_length=100, verbose_name='ID de Transacción')),
                ('authorization_code', models.CharField(blank=True, max_length=50, verbose_name='Código de Autorización')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos')),
                ('card_brand', models.CharField(blank=True, help_text='Visa, Mastercard, etc.', max_length=20, verbose_name='Marca de Tarjeta')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta del Gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.cashregister', verbose_name='Caja Registradora')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.currency', verbose_name='Moneda del Pago')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Orden')),
                ('original_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_payments', to='payments.currency', verbose_name='Moneda Original')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Reembolso')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('reason', models.TextField(verbose_name='Razón')),
                ('refund_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Transacción de Reembolso')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta del Gateway')),
                ('approved_by', models.CharField(blank=True, max_length=100, verbose_name='Aprobado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.currency', verbose_name='Moneda')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SplitPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_payments', to='orders.order', verbose_name='Orden')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'División de Pago',
                'verbose_name_plural': 'Divisiones de Pago',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['register_number', 'opened_at'], name='payments_ca_registe_c37269_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['status'], name='payments_ca_status_035639_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency', 'is_active'], name='payments_ex_from_cu_28cc97_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['updated_at'], name='payments_ex_updated_740839_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='payments_pa_payment_a0847d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status'], name='payments_pa_payment_a6e178_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['currency'], name='payments_pa_currenc_4af16e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx'),
        ),
    ]
