# Generated by Django 5.0.1 on 2025-12-07 04:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_last_login_customer_password'),
        ('menu', '0002_alter_product_image'),
        ('orders', '0002_alter_order_status_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas Totales')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total de Órdenes')),
                ('total_customers', models.PositiveIntegerField(default=0, verbose_name='Total de Clientes Únicos')),
                ('total_items_sold', models.PositiveIntegerField(default=0, verbose_name='Total de Productos Vendidos')),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas en Efectivo')),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas con Tarjeta')),
                ('other_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otras Formas de Pago')),
                ('dine_in_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas Dine-In')),
                ('takeout_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas Takeout')),
                ('delivery_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas Delivery')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total en Descuentos')),
                ('total_tips', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total en Propinas')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Promedio por Orden')),
                ('average_items_per_order', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Productos Promedio por Orden')),
                ('total_shifts', models.PositiveIntegerField(default=0, verbose_name='Total de Turnos')),
                ('closed_shifts', models.PositiveIntegerField(default=0, verbose_name='Turnos Cerrados')),
                ('top_products', models.JSONField(blank=True, default=list, help_text='Lista de productos más vendidos con cantidad y monto', verbose_name='Productos Más Vendidos')),
                ('sales_by_hour', models.JSONField(blank=True, default=list, help_text='Ventas agrupadas por hora del día', verbose_name='Ventas por Hora')),
                ('is_closed', models.BooleanField(default=False, help_text='Indica si el día ha sido cerrado oficialmente', verbose_name='Día Cerrado')),
                ('closing_notes', models.TextField(blank=True, verbose_name='Notas de Cierre')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Generado el')),
                ('generated_by', models.CharField(blank=True, help_text='User ID o "system" si fue automático', max_length=50, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Resumen Diario',
                'verbose_name_plural': 'Resúmenes Diarios',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='pos_dailysu_date_4f64dc_idx'), models.Index(fields=['is_closed'], name='pos_dailysu_is_clos_88c50e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Código único del descuento (ej: HAPPY_HOUR)', max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo del descuento', max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed_amount', 'Monto Fijo'), ('buy_x_get_y', 'Compra X lleva Y')], max_length=20, verbose_name='Tipo de Descuento')),
                ('apply_to', models.CharField(choices=[('order', 'Orden Completa'), ('product', 'Producto Específico'), ('category', 'Categoría')], default='order', max_length=20, verbose_name='Aplicar a')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (0-100) o monto fijo según tipo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del Descuento')),
                ('minimum_purchase', models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo de compra para aplicar descuento', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Compra Mínima')),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo de descuento a aplicar', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento Máximo')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Límite total de usos. Null = ilimitado', null=True, verbose_name='Usos Máximos Totales')),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, help_text='Límite de usos por cliente. Null = ilimitado', null=True, verbose_name='Usos Máximos por Cliente')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Usos Actuales')),
                ('valid_from', models.DateTimeField(verbose_name='Válido Desde')),
                ('valid_until', models.DateTimeField(verbose_name='Válido Hasta')),
                ('valid_days', models.JSONField(blank=True, default=list, help_text='Lista de días de la semana: [0=Lun, 1=Mar, ..., 6=Dom]. Vacío = todos los días', verbose_name='Días Válidos')),
                ('valid_hours', models.JSONField(blank=True, default=dict, help_text='Rango de horas: {"start": "10:00", "end": "14:00"}. Vacío = todo el día', verbose_name='Horas Válidas')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('is_public', models.BooleanField(default=True, help_text='Si aparece en el catálogo o requiere código', verbose_name='Público')),
                ('created_by', models.CharField(blank=True, help_text='User ID de quien creó el descuento', max_length=50, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Categorías a las que aplica el descuento', related_name='discounts', to='menu.category', verbose_name='Categorías Aplicables')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Productos a los que aplica el descuento', related_name='discounts', to='menu.product', verbose_name='Productos Aplicables')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Descontado')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Original')),
                ('applied_by', models.CharField(blank=True, help_text='User ID de quien aplicó el descuento', max_length=50, verbose_name='Aplicado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_usages', to='customers.customer', verbose_name='Cliente')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='pos.discount', verbose_name='Descuento')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Uso de Descuento',
                'verbose_name_plural': 'Usos de Descuentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de Turno')),
                ('user_id', models.CharField(db_index=True, help_text='UUID del usuario desde auth-service', max_length=50, verbose_name='ID del Usuario')),
                ('user_name', models.CharField(help_text='Nombre completo del empleado', max_length=200, verbose_name='Nombre del Usuario')),
                ('user_role', models.CharField(blank=True, help_text='CASHIER, WAITER, MANAGER, etc.', max_length=50, verbose_name='Rol del Usuario')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado'), ('suspended', 'Suspendido')], db_index=True, default='open', max_length=20, verbose_name='Estado')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Efectivo Inicial')),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Efectivo Final')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Ventas')),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas en Efectivo')),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas con Tarjeta')),
                ('total_other_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otras Formas de Pago')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='Total de Transacciones')),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia entre efectivo esperado y real', max_digits=10, verbose_name='Diferencia en Caja')),
                ('opening_notes', models.TextField(blank=True, verbose_name='Notas de Apertura')),
                ('closing_notes', models.TextField(blank=True, verbose_name='Notas de Cierre')),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='payments.cashregister', verbose_name='Caja Registradora')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Número de Mesa')),
                ('name', models.CharField(blank=True, help_text='Nombre descriptivo: "Mesa VIP", "Terraza 1"', max_length=100, verbose_name='Nombre')),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Número de personas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('reserved', 'Reservada'), ('cleaning', 'Limpiando'), ('maintenance', 'Mantenimiento')], db_index=True, default='available', max_length=20, verbose_name='Estado')),
                ('section', models.CharField(blank=True, help_text='Interior, Terraza, VIP, etc.', max_length=50, verbose_name='Sección')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='Piso')),
                ('waiter_id', models.CharField(blank=True, help_text='UUID del mesero asignado', max_length=50, verbose_name='ID del Mesero')),
                ('waiter_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Mesero')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Mesa VIP')),
                ('qr_code', models.CharField(blank=True, db_index=True, help_text='Código único para el QR de la mesa', max_length=100, unique=True, verbose_name='Código QR')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_assignment', to='orders.order', verbose_name='Orden Actual')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['section', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['code'], name='pos_discoun_code_b34f61_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='pos_discoun_is_acti_7bc6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['discount_type'], name='pos_discoun_discoun_397ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['discount', 'customer'], name='pos_discoun_discoun_b85089_idx'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['order'], name='pos_discoun_order_i_4cb658_idx'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['created_at'], name='pos_discoun_created_c6205b_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['shift_number'], name='pos_shift_shift_n_df5127_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['user_id', 'opened_at'], name='pos_shift_user_id_2eecaf_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status', 'opened_at'], name='pos_shift_status_821609_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['cash_register', 'status'], name='pos_shift_cash_re_1f1bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['number'], name='pos_table_number_d2ae96_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['status'], name='pos_table_status_34582e_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['section', 'status'], name='pos_table_section_0a97f2_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['qr_code'], name='pos_table_qr_code_019dc5_idx'),
        ),
    ]
