# Generated by Django 5.0.1 on 2026-07-02 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_shift_closing_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='closing_cash_cop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Efectivo Final (COP)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='closing_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Efectivo Final (USD)'),
        ),
    ]
